// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	aspera "github.com/IBM/ibmcloud-cos-cli/aspera"

	mock "github.com/stretchr/testify/mock"
)

// AsperaTransfer is an autogenerated mock type for the AsperaTransfer type
type AsperaTransfer struct {
	mock.Mock
}

// Download provides a mock function with given fields: _a0, _a1
func (_m *AsperaTransfer) Download(_a0 context.Context, _a1 *aspera.COSInput) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *aspera.COSInput) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upload provides a mock function with given fields: _a0, _a1
func (_m *AsperaTransfer) Upload(_a0 context.Context, _a1 *aspera.COSInput) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *aspera.COSInput) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
