// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import "github.com/stretchr/testify/mock"
import "os"
import "github.com/IBM/ibmcloud-cos-cli/utils"

// FileOperations is an autogenerated mock type for the FileOperations type
type FileOperations struct {
	mock.Mock
}

// GetFileInfo provides a mock function with given fields: location
func (_m *FileOperations) GetFileInfo(location string) (os.FileInfo, error) {
	ret := _m.Called(location)

	var r0 os.FileInfo
	if rf, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = rf(location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadSeekerCloserOpen provides a mock function with given fields: location
func (_m *FileOperations) ReadSeekerCloserOpen(location string) (utils.ReadSeekerCloser, error) {
	ret := _m.Called(location)

	var r0 utils.ReadSeekerCloser
	if rf, ok := ret.Get(0).(func(string) utils.ReadSeekerCloser); ok {
		r0 = rf(location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(utils.ReadSeekerCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: location
func (_m *FileOperations) Remove(location string) error {
	ret := _m.Called(location)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteCloserOpen provides a mock function with given fields: location
func (_m *FileOperations) WriteCloserOpen(location string) (utils.WriteCloser, error) {
	ret := _m.Called(location)

	var r0 utils.WriteCloser
	if rf, ok := ret.Get(0).(func(string) utils.WriteCloser); ok {
		r0 = rf(location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(utils.WriteCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
