// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import plugin "github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin"

// Plugin is an autogenerated mock type for the Plugin type
type Plugin struct {
	mock.Mock
}

// GetMetadata provides a mock function with given fields:
func (_m *Plugin) GetMetadata() plugin.PluginMetadata {
	ret := _m.Called()

	var r0 plugin.PluginMetadata
	if rf, ok := ret.Get(0).(func() plugin.PluginMetadata); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(plugin.PluginMetadata)
	}

	return r0
}

// Run provides a mock function with given fields: c, args
func (_m *Plugin) Run(c plugin.PluginContext, args []string) {
	_m.Called(c, args)
}
