// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injectors

import (
	"github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin"
	"github.com/IBM/ibmcloud-cos-cli/di/providers"
	"github.com/IBM/ibmcloud-cos-cli/utils"
)

// Injectors from wire.go:

func InitializeCosContext(pluginContext plugin.PluginContext) (*utils.CosContext, error) {
	ui := providers.NewUI()
	pluginConfig := providers.GetPluginConfig(pluginContext)
	baseConfig := providers.GetBaseConfig(pluginContext)
	cosEndPointsWSClient, err := providers.NewCOSEndPointsWSClient(pluginContext, baseConfig)
	if err != nil {
		return nil, err
	}
	config, err := providers.NewConfig(pluginContext, cosEndPointsWSClient, baseConfig)
	if err != nil {
		return nil, err
	}
	session, err := providers.NewSession(config)
	if err != nil {
		return nil, err
	}
	v := providers.GetS3APIFn()
	fileOperationsImpl := providers.GetFileOperations()
	cosContext := &utils.CosContext{
		UI:               ui,
		Config:           pluginConfig,
		Session:          session,
		ClientGen:        v,
		ListKnownRegions: cosEndPointsWSClient,
		FileOperations:   fileOperationsImpl,
	}
	return cosContext, nil
}
