// Code generated by "stringer -type=CommandErrorCause"; DO NOT EDIT.

package errors

import "strconv"

const _CommandErrorCause_name = "BadFlagSyntaxNotDefinedFlagInvalidBooleanValueInvalidBooleanFlagMissingValueInvalidValueMissingRequiredFlag"

var _CommandErrorCause_index = [...]uint8{0, 13, 27, 46, 64, 76, 88, 107}

func (i CommandErrorCause) String() string {
	i -= 1
	if i < 0 || i >= CommandErrorCause(len(_CommandErrorCause_index)-1) {
		return "CommandErrorCause(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CommandErrorCause_name[_CommandErrorCause_index[i]:_CommandErrorCause_index[i+1]]
}
