// Code generated by "stringer -type=EndpointsErrorCause"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EndpointsRegionInvalid-1]
	_ = x[EndpointsRegionEmpty-2]
	_ = x[EndpointsStoredRegionInvalid-3]
}

const _EndpointsErrorCause_name = "EndpointsRegionInvalidEndpointsRegionEmptyEndpointsStoredRegionInvalid"

var _EndpointsErrorCause_index = [...]uint8{0, 22, 42, 70}

func (i EndpointsErrorCause) String() string {
	i -= 1
	if i < 0 || i >= EndpointsErrorCause(len(_EndpointsErrorCause_index)-1) {
		return "EndpointsErrorCause(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EndpointsErrorCause_name[_EndpointsErrorCause_index[i]:_EndpointsErrorCause_index[i+1]]
}
